"""Initial migration for duplicate contacts

Revision ID: 59a2f85daa8d
Revises: 
Create Date: 2025-03-16 17:37:02.061306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a2f85daa8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.String(length=256), nullable=False),
    sa.Column('merge_all', sa.Boolean(), nullable=False),
    sa.Column('blocked_creation', sa.Boolean(), nullable=False),
    sa.Column('duplicate_start', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'settings_id', name='uq_block_blockid_settings')
    )
    op.create_table('priority_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('action', sa.Boolean(), nullable=False),
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name', 'settings_id', name='uq_priority_fields')
    )
    op.create_table('block_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exclusion_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('block_field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_field_id'], ['block_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exclusion_fields')
    op.drop_table('block_fields')
    op.drop_table('priority_fields')
    op.drop_table('blocks')
    op.drop_table('settings')
    # ### end Alembic commands ###
