"""update field merge_is_active

Revision ID: b41e61db6311
Revises: e42d6f6390be
Create Date: 2025-03-22 19:16:06.275599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41e61db6311'
down_revision: Union[str, None] = 'e42d6f6390be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('merge_is_active', sa.Boolean(), nullable=False))
    op.drop_column('settings', 'duplicate_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('duplicate_start', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('settings', 'merge_is_active')
    # ### end Alembic commands ###
