"""Add merge_block_logs table

Revision ID: bb51b5104c90
Revises: b41e61db6311
Create Date: 2025-03-31 17:34:04.810767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb51b5104c90'
down_revision: Union[str, None] = 'b41e61db6311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_block_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.String(length=256), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_merge_block_logs_subdomain_contact_id', 'merge_block_logs', ['subdomain', 'contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_merge_block_logs_subdomain_contact_id', table_name='merge_block_logs')
    op.drop_table('merge_block_logs')
    # ### end Alembic commands ###
