"""change table priority_fields

Revision ID: be8b8bb61f55
Revises: bb51b5104c90
Create Date: 2025-04-05 22:14:47.854341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8b8bb61f55'
down_revision: Union[str, None] = 'bb51b5104c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merge_block_logs', 'contact_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_column('priority_fields', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priority_fields', sa.Column('action', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('merge_block_logs', 'contact_id',
               existing_type=sa.String(length=256),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
